### PR TITLE
custom order in pgsql using case expression

### PR DESCRIPTION
**Pull request by legend6**
custom order is now working in pgsql

### CODE REVIEW

**Comment by yaroslawww** [comment]
@legend6  Sorry, I can't merge the current implementation, as the connection name can have any string name, and the requested connection may not be "default".
If you need to override the query, please override in model the "whereRecentlyViewedIn" method or use a completely different trait.

**Comment by legend6** [comment]
we can get the driver name using DB class
DB::connection()->getPDO()->getAttribute(PDO::ATTR_DRIVER_NAME)

**Comment by legend6** [comment]
> @legend6 Sorry, I can't merge the current implementation, as the connection name can have any string name, and the requested connection may not be "default". If you need to override the query, please override in model the "whereRecentlyViewedIn" method or use a completely different trait.

we can get the driver name using DB class
DB::connection()->getPDO()->getAttribute(PDO::ATTR_DRIVER_NAME)

**Comment by yaroslawww** [comment]
@legend6  In this case it will also use default DB connection, but each model can has own connection useing `$connection` variable.

Today release version 3.0.0 where removed sorting using DB and moved to sorting using collection. https://github.com/yaroslawww/laravel-recently-viewed/blob/master/src/RecentlyViewed.php#L65 (it will take little more time, but collection limit is not big, so this is not affect server load). 

Thank you for help and pull requests!

**Pull request closed without merging**
